version: "3.8"

networks:
  traefik_traefik:
    external: true
  hostnet:
    external: true
    name: "host"

services:
  esphome:
    image: esphome/esphome:latest
    networks:
      hostnet: {}
    volumes:
    - /mnt/docker/esphome:/config
