version: "3.7"

networks:
  gitea:
    external: false
  traefik_traefik:
    external: true

services:
  server:
    image: gitea/gitea:1.7
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        window: 60s
      placement:
        constraints:
        - node.role == manager
      labels:
      - "traefik.enable=true"
      - "traefik.port=3000"
      - "traefik.docker.network=traefik_traefik"
      - "traefik.frontend.rule=Host: gitea.santorini.dokoupil.cz"
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - SSH_DOMAIN=git.santorini.dokoupil.cz
      - SSH_PORT=222
      - ROOT_URL=gitea.santorini.dokoupil.cz
      - DB_TYPE=mysql
      - DB_HOST=db:3306
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=Tn783m2R
    networks:
      - gitea
      - traefik_traefik
    volumes:
      - /mnt/ssd/docker/data/gitea:/data
    ports:
      - "222:22"

  db:
    image: mysql:5.7
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        window: 60s
      placement:
        constraints:
        - node.role == manager
    environment:
      - MYSQL_ROOT_PASSWORD=u5bmWCBj
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=Tn783m2R
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
      - /mnt/ssd/docker/data/mysql:/var/lib/mysql
