version: "3.9"

networks:
  traefik_traefik:
    external: true

services:
  helloworld:
    image: tutum/hello-world:latest
    networks:
    - default
    - traefik_traefik
    deploy:
      labels:
      - "traefik.http.routers.helloworld.rule=Host(`helloworld.sellerdale.com`)"
      - "traefik.http.routers.helloworld.entrypoints=https"
      - "traefik.http.routers.helloworld.tls=true"
      - "traefik.http.routers.helloworld.tls.certresolver=resolver"
      - "traefik.http.services.helloworld.loadbalancer.server.port=80"
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_traefik"
