version: "3.7"

networks:
  traefik_traefik:
    external: true

services:
  server:
    image: homeassistant/home-assistant:2023.1
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        window: 60s
      placement:
        constraints:
        - node.role == manager
      labels:
      - "traefik.http.routers.home-assistant.rule=Host(`home.sellerdale.com`)"
      - "traefik.http.routers.home-assistant.entrypoints=https"
      - "traefik.http.routers.home-assistant.tls=true"
      - "traefik.http.routers.home-assistant.tls.certresolver=resolver"
      - "traefik.http.services.home-assistant.loadbalancer.server.port=8123"
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_traefik"
    networks:
      - traefik_traefik
    volumes:
      - /mnt/docker/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8300:8300"
      - "51827:51827"
      - "8123:8123"
