version: "3.7"

networks:
  traefik_traefik:
    external: true

services:
  server:
    image: homeassistant/home-assistant:2022.2
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        window: 60s
      placement:
        constraints:
        - node.role == manager
      labels:
      - "traefik.http.routers.home_automation.rule=Host(`home.sellerdale.com`)"
      - "traefik.http.routers.home_automation.entrypoints=https"
      - "traefik.http.routers.home_automation.tls=true"
      - "traefik.http.routers.home_automation.tls.certresolver=resolver"
      - "traefik.http.services.home_automation.loadbalancer.server.port=8123"
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_traefik"
    networks:
      - traefik_traefik
    volumes:
      - /mnt/docker/home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8300:8300"
      - "51827:51827"
      - "8123:8123"
