version: "3.8"

services:
  mqtt:
    networks:
    - default
    image: eclipse-mosquitto:2
    volumes:
    - type: bind
      source: /mnt/docker/mqtt/data
      target: /mosquitto/data
    - type: bind
      source: /mnt/docker/mqtt/log
      target: /mosquitto/log
    - "/mnt/docker/mqtt/mqtt.conf:/mosquitto/config/mosquitto.conf"
    ports:
    - 1883:1883
    - 9001:9001
