---
version: '3.7'

networks:
  traefik_traefik:
    external: true

services:
  portainer:
    image: portainer/portainer:1.20.1
    networks:
    - default
    - traefik_traefik
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        window: 60s
      placement:
        constraints:
        - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 60s
      labels:
      - "traefik.enable=true"
      - "traefik.port=9000"
      - "traefik.docker.network=traefik_traefik"
      - "traefik.frontend.rule=Host: portainer.santorini.dokoupil.cz"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/ssd/docker/data/portainer:/data
