---
version: '3.7'

networks:
  traefik_traefik:
    external: true

services:
  prometheus:
    image: prom/prometheus:v2.7.1
    networks:
    - default
    - traefik_traefik
    deploy:
      replicas: 1
      placement:
        constraints:
        - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 60s
      labels:
      - "traefik.enable=true"
      - "traefik.port=9090"
      - "traefik.docker.network=traefik_traefik"
      - "traefik.frontend.rule=Host: prometheus.santorini.dokoupil.cz"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=8760h"
      - "--storage.tsdb.path=/prometheus"
      - "--web.external-url=https://prometheus.santorini.dokoupil.cz"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    volumes:
      - /mnt/ssd/docker/config/prometheus:/etc/prometheus:ro
      - /mnt/ssd/docker/data/prometheus:/prometheus

  grafana:
    image: grafana/grafana:5.4.3
    networks:
    - default
    - traefik_traefik
    deploy:
      replicas: 1
      placement:
        constraints:
        - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 60s
      labels:
      - "traefik.enable=true"
      - "traefik.port=3000"
      - "traefik.docker.network=traefik_traefik"
      - "traefik.frontend.rule=Host: grafana.santorini.dokoupil.cz"
    volumes:
      - /mnt/ssd/docker/config/grafana:/etc/grafana:ro
      - /mnt/ssd/docker/data/grafana:/var/lib/grafana

