version: "3.7"

networks:
  registry:
    external: false
  traefik_traefik:
    external: true

services:
  server:
    image: registry:2
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        window: 60s
      placement:
        constraints:
        - node.role == manager
      labels:
      - "traefik.enable=true"
      - "traefik.port=5000"
      - "traefik.docker.network=traefik_traefik"
      - "traefik.frontend.rule=Host: registry.santorini.dokoupil.cz"
      - "traefik.frontend.headers.customResponseHeaders=Access-Control-Allow-Origin: *"
    networks:
      - registry
      - traefik_traefik
    volumes:
      - /mnt/ssd/docker/data/registry:/var/lib/registry

  ui:
    image: joxit/docker-registry-ui:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        window: 60s
      placement:
        constraints:
        - node.role == manager
      labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_traefik"
      - "traefik.frontend.rule=Host: registry-ui.santorini.dokoupil.cz"
        #- "traefik.frontend.rule=PathPrefixStrip: /ui"
    environment:
      - REGISTRY_URL=http://server:5000
        #- URL=http://server:5000
      - DELETE_IMAGES=true
      - REGISTRY_TITLE="Jiri registry"
      - PULL_URL=https://registry.santorini.dokoupil.cz
    networks:
      - registry
      - traefik_traefik
