---
version: '3.7'
networks:
  traefik:

services:
  traefik:
    image: traefik:1.7-alpine
    ports:
    - published: 80
      target: 80
      protocol: tcp
      mode: ingress
    - published: 443
      target: 443
      protocol: tcp
      mode: ingress
    - published: 8080
      target: 8080
      protocol: tcp
      mode: ingress
    networks:
    - traefik
    deploy:
      replicas: 1
      placement:
        constraints:
        - node.role == manager
      labels:
      - "traefik.docker.network=traefik_traefik"
      - "traefik.enable=true"
      - "traefik.port=8081"
      - "traefik.frontend.rule=Host: traefik.santorini.dokoupil.cz"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /mnt/ssd/docker/config/traefik/traefik.toml:/traefik.toml
    - /mnt/ssd/docker/data/traefik/acme.json:/acme.json
