---
version: '3.8'

networks:
  traefik_traefik:
    external: true

services:
  prometheus:
    image: prom/prometheus:v2.35.0
    networks:
    - default
    - traefik_traefik
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        window: 60s
      placement:
        constraints:
        - node.role == manager
      labels:
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.sellerdale.com`)"
      - "traefik.http.routers.prometheus.entrypoints=https"
      - "traefik.http.routers.prometheus.tls=true"
      - "traefik.http.routers.prometheus.tls.certresolver=resolver"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_traefik"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=8760h"
      - "--storage.tsdb.path=/prometheus"
      - "--web.external-url=https://prometheus.sellerdale.com"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    volumes:
      - /mnt/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /mnt/docker/prometheus/data:/prometheus

  grafana:
    image: grafana/grafana:8.5.0
    networks:
    - default
    - traefik_traefik
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        window: 60s
      placement:
        constraints:
        - node.role == manager
      labels:
      - "traefik.http.routers.grafana.rule=Host(`grafana.sellerdale.com`)"
      - "traefik.http.routers.grafana.entrypoints=https"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=resolver"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_traefik"
    volumes:
      - /mnt/docker/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - /mnt/docker/grafana/data:/var/lib/grafana

  grafana-image-renderer:
    image: grafana/grafana-image-renderer:3.4.2
    networks:
    - default
    - traefik_traefik
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        window: 60s
      placement:
        constraints:
        - node.role == manager
      labels:
      - "traefik.http.routers.grafana-image-renderer.rule=Host(`grafana-image-renderer.sellerdale.com`)"
      - "traefik.http.routers.grafana-image-renderer.entrypoints=https"
      - "traefik.http.routers.grafana-image-renderer.tls=true"
      - "traefik.http.routers.grafana-image-renderer.tls.certresolver=resolver"
      - "traefik.http.services.grafana-image-renderer.loadbalancer.server.port=8081"
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_traefik"

