---
version: '3.7'

networks:
  traefik:

services:
  traefik:
    image: traefik:v2.6.1
    networks:
    - traefik
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
      - "8443:8443"
      - "9101:9101"
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        window: 60s
      placement:
        constraints:
        - node.role == manager
      replicas: 1
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.sellerdale.com`) && (PathPrefix(`/api`) || PathPrefix(`/debug`))"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=https"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=resolver"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.sellerdale.com`) && PathPrefix(`/`)"
      - "traefik.http.routers.dashboard.service=dashboard@internal"
      - "traefik.http.routers.dashboard.entrypoints=https"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=resolver"
      - "traefik.http.services.justAdummyService.loadbalancer.server.port=1337"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /mnt/docker/traefik:/etc/traefik
